# Generated by Django 4.1.5 on 2023-01-05 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('cateforyTitle', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
                ('categoryUrl', models.CharField(max_length=100)),
                ('categoryImage', models.ImageField(upload_to='category/')),
                ('categoryDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=200)),
                ('postContent', models.TextField()),
                ('postUrl', models.CharField(max_length=100)),
                ('postImage', models.ImageField(upload_to='post/')),
                ('postCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
