# Generated by Django 4.1.5 on 2023-01-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categorydate_category_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='Description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
