# Generated by Django 4.1.5 on 2023-01-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_date_posts_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Description',
        ),
    ]
