# Generated by Django 4.1.5 on 2023-01-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
