# Generated by Django 4.1.5 on 2023-01-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscribedusers_remove_posts_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
