# Generated by Django 4.1.5 on 2023-01-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_subscribedusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='Url',
            new_name='url',
        ),
    ]
